# site settings
title: Code Solutions
subtitle: Make it simple, make it memorable
email: frederick@codesolutions.be
baseurl: "/code-solutions-be" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Plankenbergstraat 38
city: Munsterbilzen
zip_code: 3740
country: België
phone: +32 (0)489 93 05 79

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 5

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/fgaens
  LinkedIn: https://www.linkedin.com/in/frederick-gaens-810163142/

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
